# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "PAGK.kr"
  identifier = "aboutpagk"
  url = "#"
  weight = 10

[[main]]
  name = "PAGK 소개"
  parent = "aboutpagk"
  url = "/aboutpagk/"
  weight = 1

[[main]]
  name = "연혁"
  parent = "aboutpagk"
  url = "/abouthistory/"
  weight = 2

[[main]]
  name = "회칙"
  parent = "aboutpagk"
  url = "/aboutpolicy/"
  weight = 3

[[main]]
  name = "운영위원회"
  parent = "aboutpagk"
  url = "/steering-committee/"
  weight = 4

[[main]]
  name = "Posts"
  url = "/post/"
  weight = 30

[[main]]
  name = "Annual Meeting"
  url = "/categories/annual-meeting/"
  weight = 40

#[[main]]
#  name = "Meetings"
#  url = "/tutorial/"
#  weight = 5

[[main]]
  name = "Slides"
  url = "/talk/"
  weight = 45

[[main]]
  name = "Photos"
  url = "/photos/"
  weight = 50

[[main]]
  name = "Groups.PAGK.kr↗"
  url = "https://groups.pagk.kr"
  weight = 60

[[main]]
  name = "Links"
  url = "/links/"
  weight = 70

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7
#
